### ISSUE TITLE
Feedback for release 3.1.4

### ISSUE THREAD

**Issue by cmarangon** [wallee-payment/php-sdk#16]
Hi wallee dev team

I just wanted to let you know that you added a non optional parameter in the function Wallee\Sdk\ApiClient::callApi() in your latest Patch Release 3.1.4.
Naturally this triggered a bunch of warnings on our end.

Next time, could you add a hint in the release notes?

Thank for your work

**Comment by theodorspringwallee** [comment]
Dear [cmarangon](https://github.com/cmarangon)

Thank you for your input. I'll forward this point of improvement to our developers.

Best regards
