### ISSUE TITLE
Can't redirect clients to my website after payment complete and can't choose payment methods at my application

### ISSUE THREAD

**Issue by ahmedmahgoup94** [wallee-payment/php-sdk#6]
Hi Ian Tring to use this library to integrate payment in laravel it is redirect me to payment methods selection page and after that card or other methods info but I want users and clients to choose  payment methods at my app and another issue I can't redirect client to app once payment complete.

**Comment by thomashunziker** [comment]
To allow the selection of the payment method within your application you have to pass the payment method configuration to use. There is a property called `allowedPaymentMethodConfigurations` which allows to restrict the payment methods available on the payment page.

To control where the user is redirected to after a payment you can use the property `successUrl` resp. `failedUrl`
